name: Professional Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: DiegoSanchez413/DiegoSanchez413@main
        with:
          WAKATIME_API_KEY: $ {{ 3be336a4-c0a1-4f84-945b-88df425cce9f }}
          GH_TOKEN: ${{ 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 }}
