name: WakaTime status update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"
jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses:  DiegoSanchez413/DiegoSanchez413@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: "main"
          COMMIT_MSG: "Update stats"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_PROFILE_VIEWS: "True"
